# Generated by Django 5.2.6 on 2025-10-10 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='comapny',
            new_name='Company',
        ),
    ]
