# Generated by Django 5.2.6 on 2025-09-15 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rdate', models.DateField()),
                ('moviename', models.CharField(max_length=100)),
                ('hero', models.CharField(max_length=100)),
                ('heroine', models.CharField(max_length=100)),
                ('rating', models.FloatField()),
            ],
        ),
    ]
