# Generated by Django 5.2.6 on 2025-10-16 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='Student1',
        ),
        migrations.RenameModel(
            old_name='Teacher',
            new_name='Teacher1',
        ),
    ]
