# Generated by Django 5.2.6 on 2025-10-16 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_rename_student_student1_rename_teacher_teacher1'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='student1',
            name='address',
        ),
        migrations.RemoveField(
            model_name='student1',
            name='email',
        ),
        migrations.RemoveField(
            model_name='student1',
            name='id',
        ),
        migrations.RemoveField(
            model_name='student1',
            name='name',
        ),
        migrations.RemoveField(
            model_name='teacher1',
            name='address',
        ),
        migrations.RemoveField(
            model_name='teacher1',
            name='email',
        ),
        migrations.RemoveField(
            model_name='teacher1',
            name='id',
        ),
        migrations.RemoveField(
            model_name='teacher1',
            name='name',
        ),
        migrations.AddField(
            model_name='student1',
            name='contactinfo1_ptr',
            field=models.OneToOneField(auto_created=True, default='', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='testapp.contactinfo1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher1',
            name='contactinfo1_ptr',
            field=models.OneToOneField(auto_created=True, default='', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='testapp.contactinfo1'),
            preserve_default=False,
        ),
    ]
